# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "piggybak"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Steph Skardal", "Brian Buchalter"]
  s.date = "2012-01-07"
  s.description = "Mountable ecommerce"
  s.email = "steph@endpoint.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/javascripts/piggybak.js",
    "app/controllers/piggybak/cart_controller.rb",
    "app/controllers/piggybak/orders_controller.rb",
    "app/helpers/piggybak_helper.rb",
    "app/mailers/piggybak/notifier.rb",
    "app/models/piggybak/address.rb",
    "app/models/piggybak/cart.rb",
    "app/models/piggybak/country.rb",
    "app/models/piggybak/credit.rb",
    "app/models/piggybak/line_item.rb",
    "app/models/piggybak/order.rb",
    "app/models/piggybak/payment.rb",
    "app/models/piggybak/payment_calculator/authorize_net.rb",
    "app/models/piggybak/payment_calculator/fake.rb",
    "app/models/piggybak/payment_method.rb",
    "app/models/piggybak/payment_method_value.rb",
    "app/models/piggybak/shipment.rb",
    "app/models/piggybak/shipping_calculator/flat_rate.rb",
    "app/models/piggybak/shipping_calculator/free.rb",
    "app/models/piggybak/shipping_calculator/range.rb",
    "app/models/piggybak/shipping_method.rb",
    "app/models/piggybak/shipping_method_value.rb",
    "app/models/piggybak/state.rb",
    "app/models/piggybak/tax_calculator/percent.rb",
    "app/models/piggybak/tax_method.rb",
    "app/models/piggybak/tax_method_value.rb",
    "app/models/piggybak/variant.rb",
    "app/views/piggybak/cart/_form.html.erb",
    "app/views/piggybak/cart/_items.html.erb",
    "app/views/piggybak/cart/show.html.erb",
    "app/views/piggybak/notifier/order_notification.text.erb",
    "app/views/piggybak/orders/_address_form.html.erb",
    "app/views/piggybak/orders/_details.html.erb",
    "app/views/piggybak/orders/download.text.erb",
    "app/views/piggybak/orders/list.html.erb",
    "app/views/piggybak/orders/no_access.text.erb",
    "app/views/piggybak/orders/receipt.html.erb",
    "app/views/piggybak/orders/show.html.erb",
    "app/views/rails_admin/main/_actions.html.erb",
    "config/routes.rb",
    "db/migrate/20111227150106_create_orders.rb",
    "db/migrate/20111227150322_create_addresses.rb",
    "db/migrate/20111227150432_create_line_items.rb",
    "db/migrate/20111227213558_create_variants.rb",
    "db/migrate/20111228231756_create_shipping_methods.rb",
    "db/migrate/20111228231806_create_payment_methods.rb",
    "db/migrate/20111228231829_create_payments.rb",
    "db/migrate/20111228231838_create_shipments.rb",
    "db/migrate/20111228235852_create_shipping_method_values.rb",
    "db/migrate/20111228235853_create_payment_method_values.rb",
    "db/migrate/20120102154050_create_tax_methods.rb",
    "db/migrate/20120102162414_create_countries.rb",
    "db/migrate/20120102162415_create_states.rb",
    "db/migrate/20120102162703_create_tax_method_values.rb",
    "db/migrate/20120104020930_populate_countries_and_states.rb",
    "db/migrate/20120106010412_create_credits.rb",
    "lib/acts_as_orderer/base.rb",
    "lib/acts_as_variant/base.rb",
    "lib/currency.rb",
    "lib/piggybak.rb",
    "lib/piggybak/config.rb",
    "piggybak.gemspec"
  ]
  s.homepage = "http://github.com/stephskardal/piggybak"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Mountable ecommerce"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<countries>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<rails_admin>, [">= 0"])
      s.add_runtime_dependency(%q<devise>, [">= 0"])
      s.add_runtime_dependency(%q<activemerchant>, [">= 0"])
      s.add_runtime_dependency(%q<countries>, [">= 0"])
    else
      s.add_dependency(%q<countries>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rails_admin>, [">= 0"])
      s.add_dependency(%q<devise>, [">= 0"])
      s.add_dependency(%q<activemerchant>, [">= 0"])
      s.add_dependency(%q<countries>, [">= 0"])
    end
  else
    s.add_dependency(%q<countries>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rails_admin>, [">= 0"])
    s.add_dependency(%q<devise>, [">= 0"])
    s.add_dependency(%q<activemerchant>, [">= 0"])
    s.add_dependency(%q<countries>, [">= 0"])
  end
end

