source 'http://rubygems.org'

gem 'rails', '3.1.3'
gem 'fastercsv'
gem 'sqlite'
gem 'execjs'
gem 'therubyracer'
gem 'paperclip'
gem 'cancan'
gem 'tzinfo'
gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem "piggybak", :path => '../../'
