source 'http://rubygems.org'

gem 'rails', '3.1.3'
gem 'sqlite3'
gem 'json'
gem 'devise'
gem 'rails_admin', :git => 'git://github.com/sferik/rails_admin.git'
gem 'piggybak', :path => '../../'
gem 'jquery-rails'
gem 'execjs'
gem 'therubyracer'

group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end
